### ISSUE TITLE
The README section for react-signature-modal code example seems wrong

### ISSUE THREAD

**Issue by waldothedeveloper** [anvilco/react-ui#14]
The README section related on how to use the `@anvilco/react-signature-modal` seems to have an `import` error based on the code example provided. In the example provided I see:

`import AnvilSignatureFrame ...` but then the React Component is `<AnvilSignatureModal />` ????

Shouldn't it be: 

`import AnvilSignatureModal from...`  so that it matches the `AnvilSignatureModal` component used? 

![image](https://github.com/anvilco/react-ui/assets/16472274/892c6d74-daa6-4d19-ab5a-756d1878776e)

**Comment by benogle** [comment]
Great catch, we'll get this fixed up
