### ISSUE TITLE
`style` prop is not exposed in TS types for `AnvilEmbedFrame`

### ISSUE THREAD

**Issue by LucasLemanowicz** [anvilco/react-ui#17]
**Describe the bug**
The `style` prop is not exposed in the `<AnvilEmbedFrame />` component properly causing type errors when using in Typescript.

**To Reproduce**
1. Add `style={{}}` prop to `<AnvilEmbedFrame />`
2. See type error

**Expected behavior**
Expect `style` prop to be exposed in Typescript definition

**Screenshots**
<img width="1012" alt="Screenshot 2023-11-13 at 11 12 44 AM" src="https://github.com/anvilco/react-ui/assets/361348/4de38baf-a3b7-4350-9f8b-1e17cdb31f39">

**Additional context**
Package: `"@anvilco/anvil-embed-frame": "^2.0.0"`
Repro: https://codesandbox.io/s/fast-dawn-gt25w4?file=/src/App.tsx

**Comment by benogle** [comment]
Thanks for the heads up, we'll look into this
