### ISSUE TITLE
React Signature Frame 90 degrees

### ISSUE THREAD

**Issue by JHanek3** [anvilco/react-ui#4]
**Describe the bug**
Using the react component SignatureFrame from "@anvilco/react-signature-frame'". The signature box is the correct orientation, the pdf that is to be filed comes in at a 90 degree angle. 

**To Reproduce**
Imported the SignatureFrame component and used it.

**Expected behavior**
What I expected to happen was the pdf would come in at the correct orientation. It is not rotated in the dashboard.

**Screenshots**
![rotate](https://user-images.githubusercontent.com/50468135/132726092-7b7079c1-e700-45b0-b730-f547f4be3f9a.PNG)

**Desktop (please complete the following information):**
 - OS: Windows10 Pro
 - Browser: 
Chrome
 - Version 93.0.4577.63 (Official Build) (64-bit)

**Additional context**
If you need more information let me know, this is my first bug report for you guys.

**Comment by benogle** [comment]
This is related to the rotations in the PDF, not this repo. Closing and we'll get you a fixed PDF

**Comment by JHanek3** [comment]
Thanks Ben, sorry for the wrong post.
